// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7gNQMSu8wIrAWbyJmM266jdUUwT-waE',
    appId: '1:980982327574:web:ed922c4cac7e9d73e1c837',
    messagingSenderId: '980982327574',
    projectId: 'gymapp-2def3',
    authDomain: 'gymapp-2def3.firebaseapp.com',
    storageBucket: 'gymapp-2def3.firebasestorage.app',
    measurementId: 'G-PWBT0Q9J36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5i4xR_S0zWvqg-8aghsTwXLMmqzpUjOY',
    appId: '1:980982327574:android:c239cf88687564e6e1c837',
    messagingSenderId: '980982327574',
    projectId: 'gymapp-2def3',
    storageBucket: 'gymapp-2def3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwtxErynfugqLAC0HumLZeiVwxRcLl4w',
    appId: '1:980982327574:ios:8a315d8b27b59d4be1c837',
    messagingSenderId: '980982327574',
    projectId: 'gymapp-2def3',
    storageBucket: 'gymapp-2def3.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwtxErynfugqLAC0HumLZeiVwxRcLl4w',
    appId: '1:980982327574:ios:8a315d8b27b59d4be1c837',
    messagingSenderId: '980982327574',
    projectId: 'gymapp-2def3',
    storageBucket: 'gymapp-2def3.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB7gNQMSu8wIrAWbyJmM266jdUUwT-waE',
    appId: '1:980982327574:web:2617247b7852bb57e1c837',
    messagingSenderId: '980982327574',
    projectId: 'gymapp-2def3',
    authDomain: 'gymapp-2def3.firebaseapp.com',
    storageBucket: 'gymapp-2def3.firebasestorage.app',
    measurementId: 'G-Q5480RTVMK',
  );
}
